### ISSUE TITLE
Missing support for nested comments.

### ISSUE THREAD

**Issue by B3rn475** [dart-atom/dart#1082]
The plugin doesn't supports nested comments

```
/* /* foo */ bar */
```

![screenshot from 2016-08-25 09 29 40](https://cloud.githubusercontent.com/assets/2686902/17977442/93f358f4-6aa6-11e6-82d1-bbab75df4c95.png)

see https://github.com/dart-lang/sdk/issues/27157

and apparently even GitHub doesn't

``` dart
/* /* foo */ bar */
```

**Comment by DanTup** [comment]
I just fixed this in Dart Code, change may be copyable:

https://github.com/Dart-Code/Dart-Code/commit/f78a8e1400e79b4d645cccf992dae98293be3476
