### ISSUE TITLE
Dart 2.4.0 Debug broken

### ISSUE THREAD

**Issue by jtmcdole** [dart-atom/dart#1191]
Connecting to the observatory's websocket requires the secret key (randomly generated):

`Observatory listening on http://127.0.0.1:16702/gO1rif8XI7g=/`

I'm on Dart 2.4.0 and building the plugin has been... an _adventure_ in failure. Editing the js directly to a built string (e.g. `ws://127.0.0.1:16702/gO1rif8XI7g=/ws`) was enough to restore debugging.

**Comment by devoncarew** [comment]
Hey John, this plugin isn't actively maintained anymore; I've updated the readme to reflect that: https://github.com/dart-atom/dart/blob/master/README.md#note.

**Comment by jtmcdole** [comment]
Sounds good (but sad). I'm usually 100% in Vim with the dart-language-server and Nate's lsc plugins, but windows is a PITA :)
